---
- name: Ensure FireHOL Is Present (Debian)
  become: true
  apt:
    name: firehol
    state: present
    update_cache: true
    cache_valid_time: 360
  when: ansible_os_family == 'Debian'

- name: Ensure FireHOL Configuration File Is Present
  template:
    src: firehol.conf.j2
    dest: /etc/firehol/firehol.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart and Enable FireHOL